### ISSUE TITLE
Bug : Bold is not working 🔴 

### ISSUE THREAD

**Issue by ujjwal3067** [jdanielmourao/obsidian-sanctum#11]
Another Bug  I found is that Bold is not working. Here is the screecast.

https://user-images.githubusercontent.com/28984548/137823647-2744c37f-3afe-44e4-8e8c-fa3c3bed37d4.mov

**Comment by jdanielmourao** [comment]
Thank you for reporting it so soon! Try updating the theme, it should be working now. ;)

**Comment by lavaldi** [comment]
I've just installed it and this bug persist

https://user-images.githubusercontent.com/1221474/138018737-bcfc7c57-b557-432f-b8c0-a940d38d6c07.mp4

**Comment by jdanielmourao** [comment]
Do me a favor, and open Style Settings, and change the editor/preview font to one you have installed on your computer (a system font is fine). See if the bold is displayed or not.

**Comment by lavaldi** [comment]
Yep, I changed the preview and editor fonts in this way :

```css
--font-preview: -apple-system, sans-serif;
--font-editor: -apple-system, sans-serif;
```

and bold works

<img width="869" alt="image" src="https://user-images.githubusercontent.com/1221474/138178687-b1a9a5a3-d959-4999-9d16-c77f9cc098ec.png">

<img width="940" alt="image" src="https://user-images.githubusercontent.com/1221474/138178717-a99e21e4-5843-4b29-a12f-f57337f698d2.png">

**Comment by jdanielmourao** [comment]
Make sure to update the theme, as I've uploaded the new file just a minute ago

**Comment by jdanielmourao** [comment]
Can you change the font same as @lavaldi , @ujjwal3067 , and see if bold works for you, then?

**Comment by ujjwal3067** [comment]
@jdanielmourao  Works with different font.

**Comment by jdanielmourao** [comment]
That's because it's a variable font, where they've fused regular and bold together, but didn't incorporate italic/slant parameters in it, hence why is has 2 variants. iA Writer Quattro S is not a variable font, so they need to divide every weight and style into separate font files. I actually forgot about the S variant. You could set that as your font, and have pretty much the same experience. Sorry, long day today!
